/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.Collections;
import java.util.List;

public class Library {
    public List someLibraryMethod(int number) {
        if (number == 1) {
            return Collections.emptyList();
        } else {
            return List.of(true);
        }
    }
}
